name: ai_539_hw
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1s=h7f8727e_0
  - python=3.9.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - ai2thor==2.5.0
      - aiohttp==3.8.3
      - aiohttp-cors==0.7.0
      - aioredis==2.0.1
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.2
      - attrs==22.2.0
      - aws-requests-auth==0.4.3
      - black==23.1.0
      - blessed==1.20.0
      - botocore==1.29.69
      - cachetools==5.3.0
      - charset-normalizer==2.1.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - colour==0.1.5
      - contourpy==1.0.7
      - cycler==0.11.0
      - descartes==1.1.0
      #- detectron2==0.6
      - easydict==1.9
      - filelock==3.9.0
      - flask==2.2.2
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fst-pso==1.8.1
      - future==0.18.3
      - fuzzytm==2.0.5
      - fvcore==0.1.5.post20221221
      - gensim==4.3.0
      - google-api-core==2.11.0
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - googleapis-common-protos==1.58.0
      - gpustat==1.0.0
      - grpcio==1.51.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - h5py==3.8.0
      - hydra-core==1.3.1
      - idna==3.4
      - imageio==2.25.0
      - importlib-metadata==6.0.0
      - iopath==0.1.9
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - jsonschema==4.17.3
      - kiwisolver==1.4.4
      - machine-common-sense==0.6.4
      - markdown==3.4.1
      - markdown-it-py==2.1.0
      - markupsafe==2.1.2
      - matplotlib==3.6.3
      - mdurl==0.1.2
      - miniful==0.0.6
      - msgpack==1.0.4
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - networkx==3.0
      - nltk==3.8.1
      - numpy==1.23.5
      - numpy-indexed==0.3.5
      - numpy-quaternion==2020.5.19.15.27.24
      - numpyencoder==0.3.0
      - nvidia-ml-py==11.495.46
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencensus==0.11.1
      - opencensus-context==0.1.3
      - opencv-python==4.7.0.68
      - packaging==23.0
      - pandas==1.5.3
      - pathfinding==1.0.1
      - pathspec==0.11.0
      - pillow==9.4.0
      - pip==23.0
      - platformdirs==3.0.0
      - portalocker==2.7.0
      - progressbar2==4.2.0
      - prometheus-client==0.16.0
      - protobuf==4.21.12
      - psutil==5.9.4
      - py-spy==0.3.14
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycocotools==2.0.6
      - pydantic==1.10.4
      - pyfume==0.2.25
      - pygments==2.14.0
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-utils==3.5.2
      - pytreebank==0.2.7
      - pytz==2022.7.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - ray==1.4.1
      - redis==4.5.1
      - regex==2022.10.31
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rich==13.3.1
      - rsa==4.9
      - scikit-image==0.19.3
      - scipy==1.10.0
      - setuptools==67.2.0
      - shapely==1.7.1
      - simpful==2.9.0
      - six==1.16.0
      - smart-open==6.3.0
      - tabulate==0.9.0
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.2.0
      - tifffile==2023.2.3
      - tomli==2.0.1
      - torch==1.13.1
      - torchtext==0.6.0
      #- torchvision==0.13.1+cu113
      - tqdm==4.64.1
      - typeguard==2.13.3
      - typing-extensions==4.4.0
      - urllib3==1.26.14
      - wcwidth==0.2.6
      - werkzeug==2.2.2
      - wheel==0.38.4
      - yacs==0.1.8
      - yarl==1.8.2
      - zipp==3.13.0
prefix: /home/matthew/miniconda3/envs/ai_539_hw
